name: silaty # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: A neat prayer reminder app # 79 char long summary
description: |
  A neat prayer reminder app

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

compression: lzo

parts:
  silaty:
    plugin: python
    python-version: python3
    source: .
    build-packages:
      - python3-pip
      - libpulse-dev
    stage-packages:
      - gir1.2-gtk-3.0
      - gir1.2-appindicator3-0.1
      - gir1.2-notify-0.7
      - libgstreamer1.0-0
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-pulseaudio
      - python3-gst-1.0
      - libpulse0
      - libglu1-mesa
      - freeglut3
      - libgpm2
      - libslang2
    python-packages:
      - setuptools
      - PyGObject
      - pip
      - wheel
    override-stage: |
      # copy project files
      cp -r $SNAPCRAFT_PART_BUILD/* $SNAPCRAFT_PART_INSTALL
      # copy icons
      cp $SNAPCRAFT_PART_BUILD/silaty-indicator.py $SNAPCRAFT_PART_INSTALL/silaty-indicator
      cp $SNAPCRAFT_PART_BUILD/icons/hicolor/128x128/apps/silaty.svg $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/scalable/apps/
      cp $SNAPCRAFT_PART_BUILD/icons/hicolor/128x128/apps/silaty.svg $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/128x128/apps/
      cp $SNAPCRAFT_PART_BUILD/icons/hicolor/48x48/apps/silaty.svg $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/48x48/apps/
      cp $SNAPCRAFT_PART_BUILD/icons/hicolor/24x24/apps/silaty.svg $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/24x24/apps/
      snapcraftctl stage

apps:
  silaty:
    command: usr/bin/python3 $SNAP/silaty-indicator
    desktop: $SNAPCRAFT_PROJECT_DIR/silaty.desktop
    extensions: [gnome-3-34]
    plugs:
      - desktop
      - audio-playback
    slots:
      - dbus-daemon
    common-id: com.github.AXeL-dev.silaty

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.github.AXeL-dev.silaty
